import streamlit as st
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from utils import (call_agent, extract_agent_text, get_risk_summary,
                   badge_html, escape_dollars)

st.markdown(
    '<p style="color:#546E7A;font-size:0.9rem;margin-bottom:-8px;">SentinelAI</p>'
    '<h1 style="margin-top:0;">AI Investigation Copilot</h1>',
    unsafe_allow_html=True,
)

df_summary = get_risk_summary()
cust_options = df_summary["CUSTOMER_ID"].tolist() if not df_summary.empty else ["CUST-1042"]
idx = cust_options.index(st.session_state.get("selected_customer", "CUST-1042")) \
    if st.session_state.get("selected_customer") in cust_options else 0
selected = st.selectbox("Select customer", cust_options, index=idx)
st.session_state.selected_customer = selected

st.markdown("**Suggested prompts:**")
prompt_cols = st.columns(3)
prompts = [
    f"Investigate {selected}",
    f"Why was {selected} flagged?",
    f"Show the evidence supporting {selected}'s highest-risk signals.",
]
prompts2 = [
    f"What policy guidance applies to {selected}?",
    f"Give me an evidence-backed recommendation for {selected}.",
]

for i, p in enumerate(prompts):
    if prompt_cols[i].button(p, key=f"sp_{i}", use_container_width=True):
        st.session_state.agent_question = p

p2_cols = st.columns(3)
for i, p in enumerate(prompts2):
    if p2_cols[i].button(p, key=f"sp2_{i}", use_container_width=True):
        st.session_state.agent_question = p

st.markdown("---")
question = st.text_input(
    "Ask a question about this customer",
    value=st.session_state.get("agent_question", ""),
    placeholder=f"e.g. Investigate {selected}",
)

if st.button("Run Investigation", type="primary", disabled=not question):
    st.session_state.agent_question = question
    with st.spinner("SentinelAI is investigating..."):
        try:
            response = call_agent(question)
            st.session_state.agent_response = response
        except Exception as e:
            st.session_state.pop("agent_response", None)
            st.error(f"Investigation could not be completed: {e}")

if "agent_response" in st.session_state:
    response = st.session_state.agent_response
    text = extract_agent_text(response)

    st.markdown("---")
    st.markdown(f'{badge_html("ai")} &nbsp; **Investigation Results**',
                unsafe_allow_html=True)
    if text.strip():
        st.markdown(escape_dollars(text))
    else:
        st.warning(
            "No sufficient evidence was found. The agent could not produce an "
            "investigation report for this query. This may indicate the customer "
            "does not exist or has no associated risk data."
        )

    with st.expander("Why SentinelAI produced this result"):
        st.markdown(f"""
{badge_html("fact")} **Structured data** queried from `SENTINEL_AI_DB` via the
semantic view `SENTINEL_INVESTIGATION_VIEW` using Cortex Analyst (text-to-SQL).

{badge_html("signal")} **Risk signals** come from the deterministic detection engine
(`RISK.RISK_SIGNALS`), not from the LLM.

{badge_html("policy")} **Policy evidence** retrieved from `SENTINEL_POLICY_SEARCH`
via Cortex Search (semantic retrieval).

{badge_html("ai")} **Narrative text** was generated by the Cortex Agent
(`SENTINEL_INVESTIGATION_AGENT`) grounded in the above evidence.

{badge_html("decision")} **Final determination** must be made by a qualified
compliance analyst after reviewing all evidence.
        """, unsafe_allow_html=True)
